import { UserContextProvider } from "@/context/userContext";
import { YoutubeApiContextProvider } from "@/context/youtubeApi";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <UserContextProvider>
        <YoutubeApiContextProvider>{children}</YoutubeApiContextProvider>
      </UserContextProvider>
    </div>
  );
}
